global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8091']

  - job_name: 'stock-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8092']

  - job_name: 'eureka-server-1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8761']

  - job_name: 'eureka-server-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8762']

  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080']

  - job_name: 'stock-service-2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8093']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert.rules.yml"
