spring:
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)
server:
  port: 8091
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    slo:
      http:
        server:
          requests: 50ms, 100ms, 200ms, 500ms, 1s

  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
