server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to ProductService
        - id: product-service
          uri: http://localhost:8091/
          predicates:
            - Path=/product/**

        # Route to StockService
        - id: stock-service
          uri: http://localhost:8092/
          predicates:
            - Path=/stock/**

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/, http://localhost:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true