spring:
  application:
    name: stock-service
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)
server:
  port: 8092
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true